/* tslint:disable */
/* eslint-disable */
/**
 * Limitless – Team Updates API
 * AI-powered multi-tenant team updates with hybrid retrieval and grounded LLM answers.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from './configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction, replaceWithSerializableTypeIfNeeded } from './common';
import type { RequestArgs } from './base';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, BaseAPI, RequiredError, operationServerMap } from './base';

export interface HTTPValidationError {
    'detail'?: Array<ValidationError>;
}
/**
 * Public info shown on the /join page before the user accepts.
 */
export interface InvitePreview {
    'token': string;
    'tenant_name': string;
}
export interface InviteResponse {
    'token': string;
    'tenant_id': string;
    'created_at': string;
}
export interface LocationInner {
}
export interface MessageCreate {
    'content': string;
    'event_time'?: string | null;
}
export interface MessageListResponse {
    'total': number;
    'page': number;
    'limit': number;
    'items': Array<MessageResponse>;
}
export interface MessageResponse {
    'id': string;
    'tenant_id': string;
    'user_id': string;
    'user_name': string;
    'content': string;
    'event_time': string;
    'ingested_at': string;
}
export interface QueryRequest {
    'question': string;
}
export interface QueryResponse {
    'answer': string;
    'supporting_message_ids': Array<string>;
    'supporting_timestamps': Array<string>;
    'supporting_user_names': Array<string>;
    'supporting_messages': Array<string>;
    'query_plan': { [key: string]: any; };
}
export interface TenantCreate {
    'name': string;
}
export interface TenantResponse {
    'id': string;
    'name': string;
    'created_at': string;
}
export interface UserCreate {
    'tenant_id': string;
    'name': string;
}
export interface UserResponse {
    'id': string;
    'tenant_id': string;
    'name': string;
    'created_at': string;
}
export interface ValidationError {
    'loc': Array<LocationInner>;
    'msg': string;
    'type': string;
}

/**
 * DefaultApi - axios parameter creator
 */
export const DefaultApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary Health
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        healthHealthGet: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/health`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * DefaultApi - functional programming interface
 */
export const DefaultApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = DefaultApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @summary Health
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async healthHealthGet(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<{ [key: string]: string | null; }>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.healthHealthGet(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DefaultApi.healthHealthGet']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * DefaultApi - factory interface
 */
export const DefaultApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = DefaultApiFp(configuration)
    return {
        /**
         * 
         * @summary Health
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        healthHealthGet(options?: RawAxiosRequestConfig): AxiosPromise<{ [key: string]: string | null; }> {
            return localVarFp.healthHealthGet(options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * DefaultApi - object-oriented interface
 */
export class DefaultApi extends BaseAPI {
    /**
     * 
     * @summary Health
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public healthHealthGet(options?: RawAxiosRequestConfig) {
        return DefaultApiFp(this.configuration).healthHealthGet(options).then((request) => request(this.axios, this.basePath));
    }
}



/**
 * InvitesApi - axios parameter creator
 */
export const InvitesApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * Move the authenticated user into the org identified by the invite token.  If the user was auto-provisioned into their own solo tenant during this very first login (tenant name == their email), that solo tenant is left as-is — it will simply have no users.  The user\'s tenant_id is updated to the invite\'s tenant.
         * @summary Accept Invite
         * @param {string} token 
         * @param {string | null} [authorization] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        acceptInviteInvitesTokenAcceptPost: async (token: string, authorization?: string | null, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'token' is not null or undefined
            assertParamExists('acceptInviteInvitesTokenAcceptPost', 'token', token)
            const localVarPath = `/invites/{token}/accept`
                .replace(`{${"token"}}`, encodeURIComponent(String(token)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Accept'] = 'application/json';

            if (authorization != null) {
                localVarHeaderParameter['authorization'] = String(authorization);
            }
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Generate an invite token for the current user\'s org.
         * @summary Create Invite
         * @param {string | null} [authorization] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createInviteInvitesPost: async (authorization?: string | null, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/invites/`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Accept'] = 'application/json';

            if (authorization != null) {
                localVarHeaderParameter['authorization'] = String(authorization);
            }
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Return org name for the join page — no auth required.
         * @summary Preview Invite
         * @param {string} token 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        previewInviteInvitesTokenGet: async (token: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'token' is not null or undefined
            assertParamExists('previewInviteInvitesTokenGet', 'token', token)
            const localVarPath = `/invites/{token}`
                .replace(`{${"token"}}`, encodeURIComponent(String(token)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * InvitesApi - functional programming interface
 */
export const InvitesApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = InvitesApiAxiosParamCreator(configuration)
    return {
        /**
         * Move the authenticated user into the org identified by the invite token.  If the user was auto-provisioned into their own solo tenant during this very first login (tenant name == their email), that solo tenant is left as-is — it will simply have no users.  The user\'s tenant_id is updated to the invite\'s tenant.
         * @summary Accept Invite
         * @param {string} token 
         * @param {string | null} [authorization] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async acceptInviteInvitesTokenAcceptPost(token: string, authorization?: string | null, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.acceptInviteInvitesTokenAcceptPost(token, authorization, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['InvitesApi.acceptInviteInvitesTokenAcceptPost']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Generate an invite token for the current user\'s org.
         * @summary Create Invite
         * @param {string | null} [authorization] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async createInviteInvitesPost(authorization?: string | null, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<InviteResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.createInviteInvitesPost(authorization, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['InvitesApi.createInviteInvitesPost']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Return org name for the join page — no auth required.
         * @summary Preview Invite
         * @param {string} token 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async previewInviteInvitesTokenGet(token: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<InvitePreview>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.previewInviteInvitesTokenGet(token, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['InvitesApi.previewInviteInvitesTokenGet']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * InvitesApi - factory interface
 */
export const InvitesApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = InvitesApiFp(configuration)
    return {
        /**
         * Move the authenticated user into the org identified by the invite token.  If the user was auto-provisioned into their own solo tenant during this very first login (tenant name == their email), that solo tenant is left as-is — it will simply have no users.  The user\'s tenant_id is updated to the invite\'s tenant.
         * @summary Accept Invite
         * @param {InvitesApiAcceptInviteInvitesTokenAcceptPostRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        acceptInviteInvitesTokenAcceptPost(requestParameters: InvitesApiAcceptInviteInvitesTokenAcceptPostRequest, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.acceptInviteInvitesTokenAcceptPost(requestParameters.token, requestParameters.authorization, options).then((request) => request(axios, basePath));
        },
        /**
         * Generate an invite token for the current user\'s org.
         * @summary Create Invite
         * @param {InvitesApiCreateInviteInvitesPostRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createInviteInvitesPost(requestParameters: InvitesApiCreateInviteInvitesPostRequest = {}, options?: RawAxiosRequestConfig): AxiosPromise<InviteResponse> {
            return localVarFp.createInviteInvitesPost(requestParameters.authorization, options).then((request) => request(axios, basePath));
        },
        /**
         * Return org name for the join page — no auth required.
         * @summary Preview Invite
         * @param {InvitesApiPreviewInviteInvitesTokenGetRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        previewInviteInvitesTokenGet(requestParameters: InvitesApiPreviewInviteInvitesTokenGetRequest, options?: RawAxiosRequestConfig): AxiosPromise<InvitePreview> {
            return localVarFp.previewInviteInvitesTokenGet(requestParameters.token, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * Request parameters for acceptInviteInvitesTokenAcceptPost operation in InvitesApi.
 */
export interface InvitesApiAcceptInviteInvitesTokenAcceptPostRequest {
    readonly token: string

    readonly authorization?: string | null
}

/**
 * Request parameters for createInviteInvitesPost operation in InvitesApi.
 */
export interface InvitesApiCreateInviteInvitesPostRequest {
    readonly authorization?: string | null
}

/**
 * Request parameters for previewInviteInvitesTokenGet operation in InvitesApi.
 */
export interface InvitesApiPreviewInviteInvitesTokenGetRequest {
    readonly token: string
}

/**
 * InvitesApi - object-oriented interface
 */
export class InvitesApi extends BaseAPI {
    /**
     * Move the authenticated user into the org identified by the invite token.  If the user was auto-provisioned into their own solo tenant during this very first login (tenant name == their email), that solo tenant is left as-is — it will simply have no users.  The user\'s tenant_id is updated to the invite\'s tenant.
     * @summary Accept Invite
     * @param {InvitesApiAcceptInviteInvitesTokenAcceptPostRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public acceptInviteInvitesTokenAcceptPost(requestParameters: InvitesApiAcceptInviteInvitesTokenAcceptPostRequest, options?: RawAxiosRequestConfig) {
        return InvitesApiFp(this.configuration).acceptInviteInvitesTokenAcceptPost(requestParameters.token, requestParameters.authorization, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Generate an invite token for the current user\'s org.
     * @summary Create Invite
     * @param {InvitesApiCreateInviteInvitesPostRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public createInviteInvitesPost(requestParameters: InvitesApiCreateInviteInvitesPostRequest = {}, options?: RawAxiosRequestConfig) {
        return InvitesApiFp(this.configuration).createInviteInvitesPost(requestParameters.authorization, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Return org name for the join page — no auth required.
     * @summary Preview Invite
     * @param {InvitesApiPreviewInviteInvitesTokenGetRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public previewInviteInvitesTokenGet(requestParameters: InvitesApiPreviewInviteInvitesTokenGetRequest, options?: RawAxiosRequestConfig) {
        return InvitesApiFp(this.configuration).previewInviteInvitesTokenGet(requestParameters.token, options).then((request) => request(this.axios, this.basePath));
    }
}



/**
 * MessagesApi - axios parameter creator
 */
export const MessagesApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary Create Message
         * @param {MessageCreate} messageCreate 
         * @param {string | null} [authorization] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createMessageMessagesPost: async (messageCreate: MessageCreate, authorization?: string | null, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'messageCreate' is not null or undefined
            assertParamExists('createMessageMessagesPost', 'messageCreate', messageCreate)
            const localVarPath = `/messages/`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = 'application/json';

            if (authorization != null) {
                localVarHeaderParameter['authorization'] = String(authorization);
            }
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(messageCreate, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary List Messages
         * @param {number} [limit] 
         * @param {number} [page] 
         * @param {string | null} [authorization] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        listMessagesMessagesGet: async (limit?: number, page?: number, authorization?: string | null, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/messages/`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (limit !== undefined) {
                localVarQueryParameter['limit'] = limit;
            }

            if (page !== undefined) {
                localVarQueryParameter['page'] = page;
            }

            localVarHeaderParameter['Accept'] = 'application/json';

            if (authorization != null) {
                localVarHeaderParameter['authorization'] = String(authorization);
            }
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * MessagesApi - functional programming interface
 */
export const MessagesApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = MessagesApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @summary Create Message
         * @param {MessageCreate} messageCreate 
         * @param {string | null} [authorization] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async createMessageMessagesPost(messageCreate: MessageCreate, authorization?: string | null, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<MessageResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.createMessageMessagesPost(messageCreate, authorization, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['MessagesApi.createMessageMessagesPost']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary List Messages
         * @param {number} [limit] 
         * @param {number} [page] 
         * @param {string | null} [authorization] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async listMessagesMessagesGet(limit?: number, page?: number, authorization?: string | null, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<MessageListResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.listMessagesMessagesGet(limit, page, authorization, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['MessagesApi.listMessagesMessagesGet']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * MessagesApi - factory interface
 */
export const MessagesApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = MessagesApiFp(configuration)
    return {
        /**
         * 
         * @summary Create Message
         * @param {MessagesApiCreateMessageMessagesPostRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createMessageMessagesPost(requestParameters: MessagesApiCreateMessageMessagesPostRequest, options?: RawAxiosRequestConfig): AxiosPromise<MessageResponse> {
            return localVarFp.createMessageMessagesPost(requestParameters.messageCreate, requestParameters.authorization, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary List Messages
         * @param {MessagesApiListMessagesMessagesGetRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        listMessagesMessagesGet(requestParameters: MessagesApiListMessagesMessagesGetRequest = {}, options?: RawAxiosRequestConfig): AxiosPromise<MessageListResponse> {
            return localVarFp.listMessagesMessagesGet(requestParameters.limit, requestParameters.page, requestParameters.authorization, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * Request parameters for createMessageMessagesPost operation in MessagesApi.
 */
export interface MessagesApiCreateMessageMessagesPostRequest {
    readonly messageCreate: MessageCreate

    readonly authorization?: string | null
}

/**
 * Request parameters for listMessagesMessagesGet operation in MessagesApi.
 */
export interface MessagesApiListMessagesMessagesGetRequest {
    readonly limit?: number

    readonly page?: number

    readonly authorization?: string | null
}

/**
 * MessagesApi - object-oriented interface
 */
export class MessagesApi extends BaseAPI {
    /**
     * 
     * @summary Create Message
     * @param {MessagesApiCreateMessageMessagesPostRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public createMessageMessagesPost(requestParameters: MessagesApiCreateMessageMessagesPostRequest, options?: RawAxiosRequestConfig) {
        return MessagesApiFp(this.configuration).createMessageMessagesPost(requestParameters.messageCreate, requestParameters.authorization, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary List Messages
     * @param {MessagesApiListMessagesMessagesGetRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public listMessagesMessagesGet(requestParameters: MessagesApiListMessagesMessagesGetRequest = {}, options?: RawAxiosRequestConfig) {
        return MessagesApiFp(this.configuration).listMessagesMessagesGet(requestParameters.limit, requestParameters.page, requestParameters.authorization, options).then((request) => request(this.axios, this.basePath));
    }
}



/**
 * QueryApi - axios parameter creator
 */
export const QueryApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary Query Updates
         * @param {QueryRequest} queryRequest 
         * @param {string | null} [authorization] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        queryUpdatesQueryPost: async (queryRequest: QueryRequest, authorization?: string | null, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'queryRequest' is not null or undefined
            assertParamExists('queryUpdatesQueryPost', 'queryRequest', queryRequest)
            const localVarPath = `/query/`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = 'application/json';

            if (authorization != null) {
                localVarHeaderParameter['authorization'] = String(authorization);
            }
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(queryRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * QueryApi - functional programming interface
 */
export const QueryApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = QueryApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @summary Query Updates
         * @param {QueryRequest} queryRequest 
         * @param {string | null} [authorization] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async queryUpdatesQueryPost(queryRequest: QueryRequest, authorization?: string | null, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<QueryResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.queryUpdatesQueryPost(queryRequest, authorization, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['QueryApi.queryUpdatesQueryPost']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * QueryApi - factory interface
 */
export const QueryApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = QueryApiFp(configuration)
    return {
        /**
         * 
         * @summary Query Updates
         * @param {QueryApiQueryUpdatesQueryPostRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        queryUpdatesQueryPost(requestParameters: QueryApiQueryUpdatesQueryPostRequest, options?: RawAxiosRequestConfig): AxiosPromise<QueryResponse> {
            return localVarFp.queryUpdatesQueryPost(requestParameters.queryRequest, requestParameters.authorization, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * Request parameters for queryUpdatesQueryPost operation in QueryApi.
 */
export interface QueryApiQueryUpdatesQueryPostRequest {
    readonly queryRequest: QueryRequest

    readonly authorization?: string | null
}

/**
 * QueryApi - object-oriented interface
 */
export class QueryApi extends BaseAPI {
    /**
     * 
     * @summary Query Updates
     * @param {QueryApiQueryUpdatesQueryPostRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public queryUpdatesQueryPost(requestParameters: QueryApiQueryUpdatesQueryPostRequest, options?: RawAxiosRequestConfig) {
        return QueryApiFp(this.configuration).queryUpdatesQueryPost(requestParameters.queryRequest, requestParameters.authorization, options).then((request) => request(this.axios, this.basePath));
    }
}



/**
 * TenantsApi - axios parameter creator
 */
export const TenantsApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary Create Tenant
         * @param {TenantCreate} tenantCreate 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createTenantTenantsPost: async (tenantCreate: TenantCreate, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'tenantCreate' is not null or undefined
            assertParamExists('createTenantTenantsPost', 'tenantCreate', tenantCreate)
            const localVarPath = `/tenants/`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(tenantCreate, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * TenantsApi - functional programming interface
 */
export const TenantsApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = TenantsApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @summary Create Tenant
         * @param {TenantCreate} tenantCreate 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async createTenantTenantsPost(tenantCreate: TenantCreate, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<TenantResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.createTenantTenantsPost(tenantCreate, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['TenantsApi.createTenantTenantsPost']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * TenantsApi - factory interface
 */
export const TenantsApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = TenantsApiFp(configuration)
    return {
        /**
         * 
         * @summary Create Tenant
         * @param {TenantsApiCreateTenantTenantsPostRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createTenantTenantsPost(requestParameters: TenantsApiCreateTenantTenantsPostRequest, options?: RawAxiosRequestConfig): AxiosPromise<TenantResponse> {
            return localVarFp.createTenantTenantsPost(requestParameters.tenantCreate, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * Request parameters for createTenantTenantsPost operation in TenantsApi.
 */
export interface TenantsApiCreateTenantTenantsPostRequest {
    readonly tenantCreate: TenantCreate
}

/**
 * TenantsApi - object-oriented interface
 */
export class TenantsApi extends BaseAPI {
    /**
     * 
     * @summary Create Tenant
     * @param {TenantsApiCreateTenantTenantsPostRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public createTenantTenantsPost(requestParameters: TenantsApiCreateTenantTenantsPostRequest, options?: RawAxiosRequestConfig) {
        return TenantsApiFp(this.configuration).createTenantTenantsPost(requestParameters.tenantCreate, options).then((request) => request(this.axios, this.basePath));
    }
}



/**
 * UsersApi - axios parameter creator
 */
export const UsersApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary Create User
         * @param {UserCreate} userCreate 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createUserUsersPost: async (userCreate: UserCreate, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'userCreate' is not null or undefined
            assertParamExists('createUserUsersPost', 'userCreate', userCreate)
            const localVarPath = `/users/`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(userCreate, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary List Users
         * @param {string | null} [authorization] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        listUsersUsersGet: async (authorization?: string | null, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/users/`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Accept'] = 'application/json';

            if (authorization != null) {
                localVarHeaderParameter['authorization'] = String(authorization);
            }
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * UsersApi - functional programming interface
 */
export const UsersApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = UsersApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @summary Create User
         * @param {UserCreate} userCreate 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async createUserUsersPost(userCreate: UserCreate, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<UserResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.createUserUsersPost(userCreate, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['UsersApi.createUserUsersPost']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary List Users
         * @param {string | null} [authorization] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async listUsersUsersGet(authorization?: string | null, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<UserResponse>>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.listUsersUsersGet(authorization, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['UsersApi.listUsersUsersGet']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * UsersApi - factory interface
 */
export const UsersApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = UsersApiFp(configuration)
    return {
        /**
         * 
         * @summary Create User
         * @param {UsersApiCreateUserUsersPostRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createUserUsersPost(requestParameters: UsersApiCreateUserUsersPostRequest, options?: RawAxiosRequestConfig): AxiosPromise<UserResponse> {
            return localVarFp.createUserUsersPost(requestParameters.userCreate, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary List Users
         * @param {UsersApiListUsersUsersGetRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        listUsersUsersGet(requestParameters: UsersApiListUsersUsersGetRequest = {}, options?: RawAxiosRequestConfig): AxiosPromise<Array<UserResponse>> {
            return localVarFp.listUsersUsersGet(requestParameters.authorization, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * Request parameters for createUserUsersPost operation in UsersApi.
 */
export interface UsersApiCreateUserUsersPostRequest {
    readonly userCreate: UserCreate
}

/**
 * Request parameters for listUsersUsersGet operation in UsersApi.
 */
export interface UsersApiListUsersUsersGetRequest {
    readonly authorization?: string | null
}

/**
 * UsersApi - object-oriented interface
 */
export class UsersApi extends BaseAPI {
    /**
     * 
     * @summary Create User
     * @param {UsersApiCreateUserUsersPostRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public createUserUsersPost(requestParameters: UsersApiCreateUserUsersPostRequest, options?: RawAxiosRequestConfig) {
        return UsersApiFp(this.configuration).createUserUsersPost(requestParameters.userCreate, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary List Users
     * @param {UsersApiListUsersUsersGetRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public listUsersUsersGet(requestParameters: UsersApiListUsersUsersGetRequest = {}, options?: RawAxiosRequestConfig) {
        return UsersApiFp(this.configuration).listUsersUsersGet(requestParameters.authorization, options).then((request) => request(this.axios, this.basePath));
    }
}



